version: '3'
services:
  app:
    build:
      context: ./
      target: dev
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
    ports:
      - "8082:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "FhgVoFuOrWspc3TgBIA2K4dZGuJTPwSYBoLnNckcaxy"
      MYSQL_DATABASE: "laravel"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3906:3306
    volumes:
      - 'mysql8:/var/lib/mysql'
      - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  mysql8:
    driver: local
